#ifndef FURROVINEFURROVINE_MACRO_PASTE_H
#define FURROVINEFURROVINE_MACRO_PASTE_H

#define MACROPASTE_META(x, y) x ## y
#define MACROPASTE(x, y) MACROPASTE_META(x, y)

#endif // FURROVINEFURROVINE_MACRO_PASTE_H