#ifndef FURROVINEFURROVINE_UNIQUE_NAME_H
#define FURROVINEFURROVINE_UNIQUE_NAME_H

#include <Furrovine++/macro_paste.h>

#define FURROVINE_UNIQUE( x ) MACROPASTE(x, __COUNTER__)

#endif // FURROVINEFURROVINE_UNIQUE_NAME_H