#pragma once

#include <Furrovine++/Platform.OS.h>
#include <Furrovine++/Platform.Configure.h>

namespace Furrovine {

#ifdef FURROVINECONFIGURETOPLATFORM

#ifdef FURROVINEWIN
#define FURROVINEDIRECTX 1
//#define FURROVINEOPENGL 1
#define FURROVINEXAUDIO 1
#define FURROVINEXINPUT 1
#define FURROVINEDIRECTWRITE 1
#define FURROVINEGDIPLUS 1
#else
#define FURROVINEOPENGL 1
#define FURROVINEOPENAL 1
#define FURROVINEFREETYPE 1
#endif // WIN

#ifdef FURROVINEDIRECTX

#define FURROVINESHADERMATRIXCOLUMNMAJOR 1

#if !(FURROVINEMATRIXCOLUMNMAJOR || FURROVINEMATRIXROWMAJOR)
#define FURROVINEMATRIXROWMAJOR 1
#endif // MATRIXROWMAJOR || MATRIXCOLUMNMAJOR 

#if !(FURROVINECOORDINATESYSTEMLEFTHANDED || FURROVINECOORDINATESYSTEMRIGHTHANDED)
#define FURROVINECOORDINATESYSTEMLEFTHANDED 1
#endif // COORDINATESYSTEMRIGHTHANDED || COORDINATESYSTEMLEFTHANDED 

#elif FURROVINEOPENGL

#define FURROVINESHADERMATRIXCOLUMNMAJOR 1

#if !(FURROVINEMATRIXCOLUMNMAJOR || FURROVINEMATRIXROWMAJOR)
#define FURROVINEMATRIXCOLUMNMAJOR 1
#endif // MATRIXROWMAJOR || MATRIXCOLUMNMAJOR 

#if !(FURROVINECOORDINATESYSTEMLEFTHANDED || FURROVINECOORDINATESYSTEMRIGHTHANDED)
#define FURROVINECOORDINATESYSTEMRIGHTHANDED 1
#endif // COORDINATESYSTEMRIGHTHANDED || COORDINATESYSTEMLEFTHANDED 
#endif // DIRECTX || OPENGL 

#ifdef FURROVINEREALDOUBLE
#else
#ifndef FURROVINEREALFLOAT
#define FURROVINEREALFLOAT 1
#endif // FURROVINEREALFLOAT 
#endif // FURROVINEREALDOUBLE 

#ifdef FURROVINEFLOATCOLOR
#else
#ifndef FURROVINEBYTECOLOR
#define FURROVINEBYTECOLOR 1
#endif // BYTECOLOR 
#endif // FLOATCOLOR || BYTECOLOR 

#endif // CONFIGURETOPLATFORM

}
 