#ifndef FURROVINESHADERTECHNIQUEDESCRIPTION_H
#define FURROVINESHADERTECHNIQUEDESCRIPTION_H

#include <Furrovine++/Graphics/ShaderTechniqueDescription.Decl.h>

#endif // FURROVINESHADERTECHNIQUEDESCRIPTION_H 